# Group 6: Productivity Prediction of Garment Employees

## Importing the libraries

In [73]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [74]:
dataset = pd.read_csv('garments_worker_productivity.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Taking care of missing data

In [75]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 4:14])
imputer.transform(X[:, 4:14])

array([[ 8.  ,  0.8 , 26.16, ...,  0.  ,  0.  , 59.  ],
       [ 1.  ,  0.75,  3.94, ...,  0.  ,  0.  ,  8.  ],
       [11.  ,  0.8 , 11.41, ...,  0.  ,  0.  , 30.5 ],
       ...,
       [ 7.  ,  0.65,  3.9 , ...,  0.  ,  0.  ,  8.  ],
       [ 9.  ,  0.75,  2.9 , ...,  0.  ,  0.  , 15.  ],
       [ 6.  ,  0.7 ,  2.9 , ...,  0.  ,  0.  ,  6.  ]])

## Encoding categorical data

### Encoding the Independent Variable

In [76]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse=False), [0,1,2,3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [77]:
print(X)

[[1.0 0.0 0.0 ... 0 0 59.0]
 [1.0 0.0 0.0 ... 0 0 8.0]
 [1.0 0.0 0.0 ... 0 0 30.5]
 ...
 [0.0 0.0 0.0 ... 0 0 8.0]
 [0.0 0.0 0.0 ... 0 0 15.0]
 [0.0 0.0 0.0 ... 0 0 6.0]]


### Encoding the Dependent Variable

In [78]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [79]:
print(y)

[798 715 586 ... 241 141  71]


## Splitting the dataset into the Training set and Test set

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 1)

## Feature Scaling

In [83]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train[:, 4:])
X_test = sc.transform(X_test[:, 4:])

## Applying PCA

In [84]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)

ValueError: ignored

## Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

## Visualising the Training set results

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = X_train, y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green', 'blue')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                c = ListedColormap(('red', 'green', 'blue'))(i), label = j)
plt.title('Logistic Regression (Training set)')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.legend()
plt.show()

## Visualising the Test set results

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = X_test, y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green', 'blue')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                c = ListedColormap(('red', 'green', 'blue'))(i), label = j)
plt.title('Logistic Regression (Test set)')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.legend()
plt.show()